config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/profile", to: "profile#profile"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :companions do
    resources :bookings, only: [:new, :create]
  end

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'booking_accept'
  get '/bookings/:id/decline', to: 'bookings#decline', as: 'booking_decline'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :companion
  validates :date, presence: true

  enum status: [ :pending, :accepted, :declined ]
end

app/models/companion.rb
class Companion < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
  has_many :companions
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def show
  #   @booking = Booking.find(params[:id])
  # end

  def new
    @companion = Companion.find(params[:companion_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @companion = Companion.find(params[:companion_id])
    @booking.companion = @companion
    @booking.status = 0

    if @booking.save
      redirect_to profile_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept

    @booking = Booking.find(params[:id])
    @booking.update(status: 1)
    redirect_to profile_path
  end

  def decline

    @booking = Booking.find(params[:id])
    @booking.update(status: 2)
    redirect_to profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:location, :date, :time)
  end
end

app/controllers/companions_controller.rb
class CompanionsController < ApplicationController
  before_action :set_companion, only: [ :show, :destroy ]

  # def index
  #   @companions = Companion.all
  # end

  def show
    @companion = Companion.find(params[:id])
  end

  def new
    @companion = Companion.new
  end

  def create
    @companion = Companion.new(companion_params)
    @companion.user = current_user

    if @companion.save
      redirect_to companion_path(@companion)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  # end

  # def update
  #   @companion.update(companion_params)
  #   redirect_to companion_path(@companion)
  # end

  def destroy
    @companion.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def set_companion
    @companion = Companion.find(params[:id])
  end

  def companion_params
    params.require(:companion).permit(:name, :companion_type, :offer_details, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:query].present?
      sql_query = "name ILIKE :query OR companion_type ILIKE :query"
      @companions = Companion.where(sql_query, query: "%#{params[:query]}%")
    else
      @companions = Companion.all
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @users = Users.all
  end

  def profile
    @user = current_user
    @companions = @user.companions
    @bookings = @user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <h1>Request your Walky</h1>

  <%= simple_form_for [@companion, @booking] do |f| %>
    <%= f.input :location, as: :select, collection: ["Berlin", "Hamburg", "Cologne"], class: "input-field" %>
    <p>Date: <%= f.date_field :date, class: "input-field" %>
    Time: <%= f.time_field :time, class: "input-field" %>  
    <%= f.submit class: "btn btn-flat"%></p>
  <% end %>

</div>

app/views/bookings/show.html.erb
<h1>Your request was successfully submitted 🎉</h1>

<p><%= @booking.companion.name %> will answer soon</p>

<blockquote><%= @booking.description %></blockquote>

<%= link_to "...Ready for another walk?", booking_path %>

app/views/companions/new.html.erb
<div class="container">
<%= simple_form_for [@companion] do |f| %>
  <%= f.input :name, label: "Name" %>
  <%= f.input :companion_type, as: :select, collection: ["Turtoise", "Chicken", "Hippo", "T-Rex", "Kangaroo"], label: "Type of Walky" %>
  <%= f.input :offer_details, label: "Details about your Walky" %>
  <%= f.input :photo, as: :file, input_html: { class: 'd-none' }, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
  <%= f.submit "Add your Walky", class: "btn btn-flat" %>
<% end %>
</div>

app/views/companions/show.html.erb
  <div class="blog-wrapper">
    <div class="blog-card-show">
      <div class="card-show-img">
      <% if @companion.photo.attached? %>
        <%= cl_image_tag @companion.photo.key, crop: :fill, class: "img"%>
        <% else %>
        <img src="https://images.unsplash.com/photo-1556316918-880f9e893822?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80"
        >
        <% end %>
        <h1><%=@companion.name%></h1>
      </div>
      <%# <div class="card-show-details"><span><i class="fa fa-calendar"></i>MAR 3</span><span><i class="fa fa-heart"></i>102</span></div> %>
      <div class="card-show-text"><p><%=@companion.offer_details%></p></div>
      <div class="read-more"><%= link_to "Book #{@companion.name}", new_companion_booking_path(@companion)%>
      </div>
    </div>
    </div>

    <%# <%= link_to "Delete this companion", companion_path(@companion), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %> 

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FINDYourWalky</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
<div class="wrapper">
  <div>
  <%= render "pages/shared/navbar" %>
    <%= yield %>
</div>
<div>
    <%= render "pages/shared/footer", class:"footer"%>
  </div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<html>
  <head>
    <title>Find your Walky!</title>
    <meta name="description" content="Find you any kind of companion in your hood - so you never have to walk alone.">
    <meta charset="utf-8">
  </head>
  <body>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1667864299172-7f5b748655ab?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class=“container”>
    <h1>Find your <strong>Walky</strong></h1>
    <p>Are you tired of walking alone?</p>
    <%= render partial: "pages/shared/search_button" %>
</div>
</div>
<div class="container">
<div class="cards-container">
      <%# <div class="cards"> %>
        <% @companions.each do |companion|  %>
          <%= render partial: "pages/shared/card", locals: { companion: companion } %>
          <%# <%= render partial: "pages/shared/card", locals: { companion: companion, image: @images.sample } %>
        <% end %>
      <%# </div> %>
  </div>
</div>
</body>
</html>

app/views/pages/shared/_card.html.erb
<%# <div class="cards-container"> %>
<%= link_to companion do %>
  <div class="card">
  <div class="card-image-container">
    <% if companion.photo.attached? %>
      <%= cl_image_tag companion.photo.key, crop: :fill , class: "card-image-container img" %>
    <% else %>
        <img
          src="https://images.unsplash.com/photo-1556316918-880f9e893822?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80"
          >
      <% end %>
    <%# <img src= <%= image %>
  </div>
    <div class="card-content">
      <h2><%=companion.name %></h2>
      <h3><%= companion.companion_type%></h3>
      <p><%=companion.offer_details%></p>
    </div>
  </div>
<%# </div> %>
<% end %>

app/views/pages/shared/_footer.html.erb
<html>
<body>
<div class="footer">
    <div class="links">
      <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
      <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
      <p>This Website is composed by Besher, Colleen, Katja & Louise! <i class="fas fa-heart"></i> at Le Wagon Berlin.</p>
    </div>
  </div>
  </body>
</html>

app/views/pages/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Profile", profile_path, class: "nav-link" %>

            <%# <a href="#" class="nav-link">Messages</a> %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "logo_dino_big_left.png", id: "logo", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Add your Walky", new_companion_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>

            </div>
          </li>
        <% else %>
        <!--li class="nav-item"-->
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/pages/shared/_search_button.html.erb
<%= form_with url: root_path, method: :get  do %>
  <div class="search">
    <%= text_field_tag :query,
      params[:query],
      class: "search-input",
      placeholder: "Find your Walky"
    %>
    <%= submit_tag "Search", class: "search-button" %>
  </div>
<% end %>
<%# class: "d-flex" %>
<%# form-control string required %>
 <%# btn-flat %>